ignore:
  - "tests/**/*"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        flags:
          - unittests
    patch:
      default:
        target: auto
        threshold: 1%
        flags:
          - unittests

comment: false
